apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    resolver 10.96.0.10 valid=5s;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri /index.html;
        }

        location /health {
            set $upstream_backend http://backend.markdownkb.svc.cluster.local:8080;
            proxy_pass $upstream_backend;
        }

        location /documents {
            set $upstream_backend http://backend.markdownkb.svc.cluster.local:8080;
            proxy_pass $upstream_backend;
        }
    }
